apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-2
  labels:
    app: calendar-2
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calendar-2
  template:
    metadata:
      labels:
        app: calendar-2
    spec:
      containers:
      - name: calendar-2
        image: registry.cosmin-lab.cloud:5000/calendar:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred2  # Numele secretului de imagine pentru pull din registry
      dnsConfig:
        options:
        - name: ndots
          value: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: calendar-2
  namespace: jenkins  # Specificăm spațiul de nume aici
  labels:
    app: calendar-2 # Modificat aici pentru a se potrivi cu etichetele din deployment
spec:
  selector:
    app: calendar-2
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer