apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
  labels:
    app: calendar
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
      - name: calendar
        image: registry.cosmin-lab.cloud:5000/calendar:1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred2  # Numele secretului de imagine pentru pull din registry
      dnsConfig:
        options:
        - name: ndots
          value: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: calendar
  namespace: jenkins  # Specificăm spațiul de nume aici
  labels:
    app: calendar  # Modificat aici pentru a se potrivi cu etichetele din deployment
spec:
  selector:
    app: calendar
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer